version: '3'
services:
  php-fpm:
    build:
      context: docker/php-fpm
    container_name: yeticave_php
    links:
      - mysql
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - default

  nginx:
    build:
      context: docker/nginx
    container_name: yeticave_nginx
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    expose:
      - 80
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mysql
    networks:
      - default

  mysql:
    image: mysql:5.7.32
    container_name: yeticave_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: nginx_proxy
